#! /usr/bin/env bash

cleanup_new()

{

echo "Some new and extra cleanup performed"

trap - SIGINT

}


cleanup_old()

{
echo "Some cleanup performed"

trap cleanup_new SIGINT

}

trap 'cleanup_old SIGINT' SIGINT

while :

do

echo "Hello"

sleep 1

done


