#! /usr/bin/env bash

count=3

until [ $count -gt 10 ]

do

echo "Hello there"

count=$((count+1))

echo "value of count=$count"

sleep 1

done
# This loop is finite and will stop running when count is greater than 10.

