#! /usr/bin/env bash
# until loops run until a condition is true
# STRUCTURE :

            # until [condition]
            # do
                # command1
                # command2
                # commandN
            # done
count=3

until [ $count -le 0  ]

do
echo "Hi there"

count=$((count+1))

echo "value of count=$count"

sleep 1

done

# This until loot is infinite since condition will never be true.

